// React/06_routes_hotels/src/pages/details/details.jsx
/* eslint-disable jsx-a11y/img-redundant-alt */
import React from "react";
import { useLocations } from "../../context/LocationContext";
import { useParams } from "react-router-dom";
import css from "./details.module.css";

function Details() {
  const { id } = useParams();
  const housing = useLocations().find((el) => el.id === parseInt(id, 10));
  const { photo, name, state, city, availableUnits, wifi, laundry } = housing;
  return (
    <article>
      <img
        src={photo}
        alt={`Exterior photo of ${name}`}
        className={css["listing-photo"]}
      />
      <section className={css["listing-description"]}>
        <h2 className={css["listing-heading"]}>{name}</h2>
        <p className={css["listing-location"]}>
          {city}, {state}
        </p>
      </section>
      <section className={css["listing-features"]}>
        <h2 className={css["section-heading"]}>About this housing location</h2>
        <ul>
          <li>Units available: {availableUnits}</li>
          <li>Does this location have wifi: {wifi}</li>
          <li>Does this location have laundry: {laundry}</li>
        </ul>
      </section>
    </article>
  );
}

export default Details;

// Node/12_DB_Hotels/src/app/details/details.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { HousingService } from '../housing.service';
import { HousingLocation } from '../housinglocation';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';

@Component({
  selector: 'app-details',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <article>
      <img
        class="listing-photo"
        [src]="housingLocation?.photo"
        alt="Exterior photo of {{ housingLocation?.name }}"
      />
      <section class="listing-description">
        <h2 class="listing-heading">{{ housingLocation?.name }}</h2>
        <p class="listing-location">
          {{ housingLocation?.city }}, {{ housingLocation?.state }}
        </p>
      </section>
      <section class="listing-features">
        <h2 class="section-heading">About this housing location</h2>
        <ul>
          <li>Units available: {{ housingLocation?.availableUnits }}</li>
          <li>Does this location have wifi: {{ housingLocation?.wifi }}</li>
          <li>
            Does this location have laundry: {{ housingLocation?.laundry }}
          </li>
        </ul>
      </section>
      <section class="listing-apply">
        <h2 class="section-heading">Apply now to live here</h2>
        <form [formGroup]="applyForm" (submit)="submitApplication()">
          <label for="first-name">First Name</label>
          <input id="first-name" type="text" formControlName="firstName" />

          <label for="last-name">Last Name</label>
          <input id="last-name" type="text" formControlName="lastName" />

          <label for="email">Email</label>
          <input id="email" type="email" formControlName="email" />
          <button type="submit" class="primary">Apply now</button>
        </form>
      </section>
    </article>
  `,
  styleUrl: './details.component.css',
})
export class DetailsComponent {
  route: ActivatedRoute = inject(ActivatedRoute);
  housingService = inject(HousingService);
  housingLocation: HousingLocation | undefined;

  applyForm = new FormGroup({
    firstName: new FormControl(''),
    lastName: new FormControl(''),
    email: new FormControl(''),
  });

  submitApplication() {
    this.housingService.submitApplication(
      this.applyForm.value.firstName ?? '',
      this.applyForm.value.lastName ?? '',
      this.applyForm.value.email ?? ''
    );
  }

  constructor() {
    const housingLocationId = parseInt(this.route.snapshot.params['id'], 10);
    this.housingService
      .getHousingLocationById(housingLocationId)
      .then((housingLocation) => {
        this.housingLocation = housingLocation;
      });
  }
}
